// ── RAZR SPREADSHEET BASELINE DATA (2020–2021) ───────────────────────────────
// Sourced from "Copy of RAZR Spreadsheet v3-0.xlsx" Weekly Feedback sheet

export const RAZR_OPS = [
  { name:"Hello Vietnam", creator:"Millsy", year:"20", month:"June", rating:7.29, responses:7, feedback:[
    "Super fun, we did split up often but it was top tier and showed the chaos of Vietnam",
    "I enjoyed it, though communication was a bit of a poo poo but that's a squad issue, not mission. Maybe chuck in some side objectives?",
    "Had to wait a lot at start in helicopter and had a lot of random motor fire precisely at our location",
    "Good Op, felt very useful and immersed. Artillery balanced relatively well",
    "Lots of waiting, lots of zeus abusing to mass kill",
    "Loved it good work to Millsy for the effort great experience very smooth.",
    "Was a decent op, good map choice, bit laggy but not terrible.",
  ]},
  { name:"Paranoid", creator:"M1llsy", year:"20", month:"June", rating:6.14, responses:7, feedback:[
    "good enjoyed got shot alot and needed tons of medical which didnt have",
    "Squads not following objective and going rambo",
    "very dragged op",
    "Didn't quite understand what was going on at first, the first half was quite slow and boring but second half it picked up.",
    "Mission concept good. Enemy appearing from already cleared areas. Friendly fire after contact over and during extract.",
    "Bit more jumbled and incoherent compared to the first one, bit slow and confusing at stages, but eventually picked up for some action at the end.",
    "yes, jimmy hendrix would be nice",
  ]},
  { name:"Gimmie Shelter", creator:"Millsy", year:"20", month:"June", rating:6.77, responses:13, feedback:[
    "good op funny as fuck at the end, had some people almost run under the tank",
    "Decent op, confusing at stages especially beginning of town when told to clear it in general but then told to clear the East only?",
    "The FPS was cancer but I don't blame the Zeus. I'd find it interesting to see player run ARTY used in OPs. Maybe change ACE settings to make it so blacked out is not as long.",
    "mad lag compared to other ops, bad server or poor zeus management?",
    "some members had messed around too much which did not make it that enjoyable.",
    "Tank didn't get to do much. Got blamed for something my team didn't do.",
    "More medics would be nice, where definitely good parts to the op though.",
    "Fucking great op, love it and loved the music",
    "Need more medics cant fck around in combat. Too much team kills. Need more certification training.",
    "good work millsy and thanks for the good work you put into it keep up the good work buddy.",
    "Really good op, less things being placed as it lags peoples games.",
    "good op",
  ]},
  { name:"Apocalypse Imminent", creator:"Millsy", year:"20", month:"June", rating:7.92, responses:12, feedback:[
    "god op",
    "Good op fun was some confusion but still fun",
    "Haha Grenadier Go BRRRRRT",
    "Not too bad, at times pretty dull, at other times put you on the edge of your chair.",
    "Really enjoyed, Alpha worked well, good teamwork, good leadership and coordination. Excellent zeusing, nice ambushes.",
    "yeah good, just alot of friendly arty",
    "people cheatin but it was good",
    "Got friendly fired 4 times, got bullied by the rest of my squad. massacred a bunch of Vietnamese to save my bois. Fun time",
    "Great operation, however some feedback would probably be making sure areas which have been cleared do not magically appear with enemies.",
    "Very enjoyable. Medic is fun. Reeds were fucking with the reticle which was a pain but otherwise good.",
  ]},
  { name:"Brickwall", creator:"Screen", year:"20", month:"July", rating:4.50, responses:9, feedback:[
    "screens friends got buffed shit communication wtf was going on",
    "No enemy combatants in a pve op plz. Lag was massive. lots of desync.",
    "It's a genuinely good OP ruined by Arma being Arma and the existence of players on the combatant side",
    "lots of lag and I thought I was going to a PVE op not a PVP lots of poor communication",
    "Screen made his friends OP was probably fun for them but not for us",
    "Very well planned out, OBJ's were good, NO LONG DRAWN DEFENCES. Sentient enemy combatants very annoying.",
    "dont have pvp enemy combatants, dont let enemy have grenade launchers",
    "A. Got kicked without warning. B. Very laggy, Medics are useless due to configs. C. THIS OP IS SHIT",
    "the missions and objectives were really good and kept things fun. can you do something with the respawn so we dont have so much chaos.",
  ]},
  { name:"Operation Icarus", creator:"SirDanger", year:"20", month:"July", rating:9.43, responses:7, feedback:[
    "Lots of effort, awesome operation one of the best in the past 3 months would have been better if respawn was enabled",
    "loved it",
    "Great op, great layout, brilliant objectives - the start taking a longer drawn out amount of time was frustrating, but understandable and definitely forgiven.",
    "great op very detailed it was actually one of the best of the past 4-5 months",
    "not enough napalm",
  ]},
  { name:"Bob & Weave", creator:"Brickman", year:"20", month:"July", rating:8.60, responses:10, feedback:[
    "Lots of boobs but not for me",
    "Things went smoothly this time throughout! (Except the beginning)",
    "Explosions were sad. Super fun though",
    "Somehow didn't turn to shit when lag n shit arose. the respawn made it worth it to heal but didn't punish when people did die.",
    "was aight",
    "Pretty good op nice AI but for the end defense the APC's were the only enemy I saw.",
    "Wasn't terrible",
    "Fantastic OP, massive step up from falling sky, objectives felt enjoyable and not overwhelming. Brickman really took the feedback from falling sky as a learning experience.",
    "Enjoyed it",
    "Great fun in Bravo 1 as a smaller detachment doing our own thing, clearing houses, assaulting the radio tower.",
  ]},
  { name:"Deeds of the Devil", creator:"SirDanger", year:"20", month:"July", rating:8.00, responses:8, feedback:[
    "POGGIES, thank you, it was really fun for my first milsim op",
    "Super fun. 10/10 would play again",
    "really good op desync sucked though",
    "Great op, just problems with the exfill",
    "Had a fine 10 minutes, 2 spotters for sniping was a bad idea, malt and east don't know how to shut the fuck up.",
    "Watchtower wasn't that fun, wasn't enough targets to shoot.",
    "Yes. It's very appealing to the end, aside from a few setbacks due to ARMA being ARMA.",
  ]},
  { name:"Origin Unknown", creator:"SirDanger", year:"20", month:"August", rating:8.80, responses:10, feedback:[
    "was funny, was getting hit by 4 demons and not dying",
    "Super fun, BTR was a bit weird. 9/10 would do again",
    "Loved it. Loved when I got touched in my ass.",
    "Real good but more zombies, needs building clearing with zombies.",
    "Had a fun op, zombies cool, got a bit tedious with dangers every now and then",
    "was pretty good and i had fun but a whole lot of not knowing what to do was kinda a hassle",
    "It was good",
    "Good op. Needs more testing. The sights we had worked horrible in the dark and fog.",
    "good use of vic with infantry",
  ]},
  { name:"New Dawn V2", creator:"SirDanger", year:"20", month:"August", rating:9.00, responses:4, feedback:[
    "Pretty good, never squad leading again",
    "Afghanistan OPs are always good OPs",
    "Very good with many good parts just some problems starting",
    "For my first operation it was amazing, excited to see what's next",
  ]},
  { name:"Hell's End", creator:"SirDanger", year:"20", month:"August", rating:7.00, responses:6, feedback:[
    "Saved so many lives, did my job, I want a medal system please",
    "Good op, some false starts and errors but nothing that could be helped",
    "Yes, there was plenty of action in this one.",
    "Love being a pilot in any op. If I ever have to fly something that is slower than my grandma's heartbeat monitor, I'll use my own rotors to slit my throat.",
    "Certain people ruining the op, too many fucking mortars and why the fuck was there a tank",
    "Boring, a lot went wrong",
  ]},
  { name:"Hours Before", creator:"SirDanger", year:"20", month:"August", rating:8.00, responses:3, feedback:[
    "Less than expected, still fun",
    "Solid placement and number of enemies, interesting era, no set direction of objectives?",
  ]},
  { name:"Queen & CAS 2", creator:"SirDanger", year:"20", month:"September", rating:7.58, responses:12, feedback:[
    "Lovely. Music intense. But lots of lag.",
    "good op, some glitchy things with buildings, i wanna fly",
    "Big bombs don't go boom. Squad stopped them",
    "felt a little directionless at times and I saw no CAS :( all seriousness was a nice op just comm's at times",
    "Fine op, patrolling was surprisingly fun for just being a glorified defense operation.",
    "tell my family i love them. had fun as EOD and will do again with sloff and dingo",
    "Having spawn right next to operations area with a 25 second respawn was a big mistake.",
    "Earthball was fucking around but everyone said, oh don't worry about it its fine and just let him continue to ruin the op",
    "The Op was well made and quite enjoyable. The frame rate was a bit bad.",
    "POG CHAMP",
    "Pre decent. Multeh was being a nonce though",
    "10/10",
  ]},
  { name:"Force Blue", creator:"SirDanger", year:"20", month:"September", rating:4.36, responses:11, feedback:[
    "shit map, hate being micromaneged",
    "If you gonna have engineers make sure no one else has BETTER MINE DETECTORS THAN THEM.",
    "Framerate, Communication & Spastics in the group made it a bit iffy, constantly just demining places got boring quick.",
    "Boring for most of the op with everyone sitting around doing nothing, then at the end no one had any clue what the fuck was going on.",
    "Some contact was enjoyable, but not enough, spent most of it just waiting for engineers to clear for mines.",
    "3 hours of op yet only ~30-40 dead enemies. Averaging about 10 enemies an hour. This op was definitely not meant for this many people.",
  ]},
  { name:"Firestarter", creator:"SirDanger", year:"20", month:"September", rating:5.00, responses:6, feedback:[
    "shit op, did jack shit the whole time, flew plane moved plane 100 meters sat there for the rest of the 2 hours",
    "It was okay with the efforts to the map, however issues with the AC130, and the trash pilots and gunners of the apache.",
    "The premise was good but execution wasn't ideal. I felt that Bravo squad got more attention as Alpha spent a lot of time waiting for orders.",
    "overall good op but better communication would be better",
  ]},
  { name:"Operation Wasteland", creator:"SirDanger", year:"20", month:"September", rating:8.46, responses:13, feedback:[
    "Good fun. Slightly retarded at stages. 8/10 would get shot by friendly RPG again.",
    "Great Op, A lot of action and death. Chaos is indeed most fun",
    "great fun, would love to come for more enjoyed playing medic",
    "The operation Planning was Good but there was barely anyone to shoot at",
    "Super fun, Super Chaotic, All problems I've noticed were the bad nades and blue on blue",
    "Fun as fuck. Especially the sniper team. very fun and a very good op.",
    "Yes. Nice n simple.",
    "quite good wish it was a bit longer i didnt kill anyone as a medic :D",
    "Good first experience on the server. Everyone was friendly and helped situate us with mods we hadn't used previously.",
    "This was my second ever op and it was really fun",
    "Really cinematic, well designed. I missed briefing so I wasn't sure what was going on.",
  ]},
  { name:"Makeshift Op", creator:"SirDanger", year:"20", month:"October", rating:8.40, responses:5, feedback:[
    "good op a bit short, you didnt need the nuke",
    "Some luls as everyone was getting stuff sorted and I was first time lead so was a little less involved, but all together a great mission",
    "FUN AF!",
    "Great op, loved the copy paste of CoD Zombies, no sarcasm, had fun.",
    "pog",
  ]},
  { name:"Killing Field", creator:"SirDanger", year:"20", month:"October", rating:7.00, responses:6, feedback:[
    "Yes. This is nice.",
    "lots of fun, everyone around me died",
    "good op, beautiful extended combat, but the ending just kinda left a fowl taste in my mouth.",
    "ehh laggy af",
  ]},
  { name:"Over The Mountains", creator:"SirDanger", year:"20", month:"October", rating:7.40, responses:5, feedback:[
    "Spastic tk's, good objective ideas, poorly executed due to player error, would have been a good op had no glitches/altercations occurred.",
    "jag left halfway through because he is wanker. teamspeak kept breaking. got bombed for some reason like 3 times.",
    "At some point the air assets randomly started blowing the hell out of me and Satan.",
    "the ambushes where quite fun added a nice challange to the op",
    "Good Op, Rainbow death repeatably purposely attempted to shoot down friendly helis.",
  ]},
  { name:"Dust Cloud", creator:"Brickman", year:"20", month:"October", rating:8.50, responses:10, feedback:[
    "Loved this OP, lots of flexibility and was smooth running",
    "Enjoyable and nice, just a few teamspeak issues and of course my computer shitting itself.",
    "Other than when attacking Zulu I really enjoyed it, a couple communication hiccups due to TS3.",
    "Disorganized, but enjoyed playing as a Bradley crew. Could've definitely done with some improvements.",
    "Great op with great potential, had a shit time due to lack of communication between squads.",
    "I really enjoyed the beginning part, But i felt the end part was chaotic.",
    "Great OP, I liked the convoy and idea of Infantry working with Bradleys.",
    "T H I S  O P  I S  G R E A T",
    "i personally enjoyed this op felt really involved and i could say its been one of the best i have attended this month",
    "Really enjoyed tonight's op did not have any issues whatsoever besides getting arma'd",
  ]},
  { name:"Jungle Fever", creator:"SirDanger", year:"20", month:"October", rating:6.44, responses:18, feedback:[
    "It was fine didnt see all of it but please the guns are so shit help",
    "nice op",
    "malaria. pretty fucking fun, didn't get to kill any civi's or pow's so that kind of sucked.",
    "a slight lack of medical supplies",
    "Ended short sadly, not sure why, for the most part good. Not enough medics, 1 medic per 20 which was pretty dumb.",
    "Two medics were useless, pure was whining constantly and bitching about not being a medic.",
    "Love it",
    "Thought it was a good OP, good work to both Danger and Jag for giving us such a well rounded operation.",
    "good op no complaints from me",
    "The behavior of some groups including AZO staff was very poor. Exceptionally excessive and aggressive Zeus control.",
    "AZO was extremely immature throughout the op.",
    "honestly, would've been a good op if AZO would mature a little as well as zeus neglecting players.",
  ]},
  { name:"The Airfield", creator:"SirDanger", year:"20", month:"November", rating:8.00, responses:10, feedback:[
    "Stamina was an issue for me. Maybe disable ACE advanced fatigue.",
    "long distance walking championship qualifying rounds 1",
    "Was an okay operation, would prefer to have stamina not depleted",
    "Tons of fun, best part was getting deepthroated by a german dive bomber",
    "Fantastic first OP with the AZO boys, despite the small amounts of lag and the Stamina, i really enjoyed the well strung together Mission.",
    "enjoyed it heaps with lag unsure if it was me or server",
    "STAMINA, STAMINA, STAMINA please fix this unlike the past 2 operations",
    "good op enjoyed",
    "Had lots of fun in todais operation looking forward to the next one campaign is fantastic so far",
  ]},
  { name:"Stepping Stone", creator:"SirDanger", year:"20", month:"November", rating:6.80, responses:5, feedback:[
    "Pretty good",
    "can we please have respawn with your loadout or atleast what you died with please and also backpacks",
    "good op had some hicups lag was there, very annoyed that i didnt get a flamethrower",
    "I make ops for the Cadian and all I can say is jungle ops fucking suck with the ai. Also please fix the medical settings.",
    "The Op was mostly pretty good except a few things like me accidentally wiping my squad with a grenade.",
  ]},
  { name:"Pacific Campaign (Iwo Jima)", creator:"SirDanger", year:"20", month:"November", rating:8.00, responses:1, feedback:[
    "Had a blast playing alongside you guys, mission structure was well done. Loved the tunnel section, and the CQC.",
  ]},
  { name:"Shadow Stalker", creator:"SirDanger", year:"20", month:"December", rating:9.33, responses:3, feedback:[
    "Amazing, Had a Lot of fun.",
    "the crawling was tedious but i liked the more serious feel to it",
    "Had great fun directing shit with the Satellite. the team listened to what ISR & Command said.",
  ]},
  { name:"Ia Drang", creator:"SirDanger", year:"21", month:"May", rating:7.62, responses:16, feedback:[
    "Frames got bad at some points but other than that it was great",
    "More explosives for friendlies",
    "Decent op, Squad communication was pretty slim and Squad organisation was pretty poor other than that pretty good.",
    "Good fun for an Arma 3 noob like me",
    "kinda far from the base to ao",
    "Look this is a good mission. a lot of shooting.",
    "Enjoyable for the first op in the campaign, good map, might consider going air next time to help bolster the roster",
    "bit of a clusterfuck, but arma always is",
    "smell of napalm in morning",
    "MY FPSSSSSSSSSSSS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "Coulda used more HUMAN arty but enemies felt super random and came out of no where",
    "Pretty well, nothing else that I can think of. Bit more communication, and pilots keeping the radio clear",
    "its was really fun defending the trench line was cool and was a cool adrenaline rush",
    "Took 45mins to start the op after start time, No set objectives, No pre mission briefing",
    "maybe have a few more clear objectives to complete",
  ]},
  { name:"Long Tan", creator:"SirDanger", year:"21", month:"May", rating:5.08, responses:12, feedback:[
    "What the fuck?",
    "Poorly run operation. all around fuck fight, sent to the wrong long tan and failed to replicate the battle in the slightest. op started an hour later while admins fucked around.",
    "fairly sure the village was blue on blue but I have no idea what happened",
    "Wrong Tan",
    "It was good because I got to shoot Chinese people.",
    "No jets, I'm sad, other than that pretty decent",
    "Sent Us to the wrong place. Ban Ice (Stibbsy) and Soviet from taking part. Also learn your battle Geography for next time.",
    "barnsey was amazing",
    "NO STAMINA, More rank dependent, and have a plan and more serious",
    "some fuckheads were throwing grenades and shooting trip mines",
    "SO. WE GOT SENT TO THE WRONG PLACE. On the map, there is a village called Xa Long Tan. I don't know how the fuck you stuff that up.",
    "not pog",
  ]},
  { name:"Firestarter (2021)", creator:"SirDanger", year:"21", month:"June", rating:9.40, responses:12, feedback:[
    "very good",
    "gud",
    "Poggers",
    "Operation itself was wonderful, server just had some slight desync issues, good selection of mods, enjoyed the loadouts and mission structure.",
    "Mortar make me horny",
    "Awesome op, really immersive, maybe at the start get an arsenal on like a helicopter that we landed on.",
    "Great op",
    "yes",
    "looked great, ran great and just a generally good op",
    "This literally made me cream in my pants. No lag, plenty of enemies to spray down, and a clear squad. The map is beautiful.",
    "Better layout with the preset kits (medics needed more blood/meds), probably more discipline.",
    "Good ambience, good teamwork, really immersive, especially with the graphics.",
  ]},
  { name:"Operation Contingency (2021)", creator:"SirDanger", year:"21", month:"June", rating:8.33, responses:6, feedback:[
    "Good Op, Charlie best squad and had a MW2 last stand by the burnt UAZ",
    "I won cuz I GL'd the nuke apparently",
    "Didn't have to Zeus that guy who shot a rocket at friendlies",
    "i got to gun down cunts ay",
    "descent could use more action and as im on a scot team give more long ranged weapons",
  ]},
  { name:"Broken Mojave", creator:"SirDanger", year:"21", month:"July", rating:8.86, responses:7, feedback:[
    "Guns were inaccurate as hell. No one else in Goliath came and I was a squad of 1. The tank fight was fun though",
    "WE NEED MORE CAS IN EVERY MISSION it was fun flying so more fly fly",
    "Honestly great. Really enjoyed it as objectives were clear, not too much restrictions or freedom.",
    "Being medic was useless. Anyone could revive and there were no ACE medical needed. BUT I HOPPED IN JAGS LANDROVER AND FUCKING GOT 3x THE AMOUNT OF KILLS.",
    "The gun accuracy was terrible with some of the mods. Was chaotic, I liked that.",
    "Arty boom boom",
    "Those setbacks made for an incredible op, good stuff!",
  ]},
  { name:"Freedom Rising (OJOC)", creator:"SirDanger", year:"21", month:"July", rating:6.67, responses:12, feedback:[
    "good",
    "Fun, small amounts of desync but went well",
    "Less sitting around a little bit",
    "Why did you even put a mortar squad",
    "TOO MANY IED",
    "better than the last ojoc",
    "literally the only issue was the lack of communication between higher ups and all the units.",
    "The Op was pretty good, as a pilot, there was a lot to do.",
    "as a horrible pilot i found this mission upsetting as i crashed 9 times through the whole op",
    "it's fun just we don't have much orders? rather it's like confusing.",
    "No atmosphere was established, the ambush we took at first was unexpected and we had no information about IEDs.",
    "nothing to do for mortar team",
  ]},
  { name:"Yellow Serpent", creator:"SirDanger", year:"21", month:"August", rating:6.50, responses:6, feedback:[
    "pretty shit - popguy",
    "In response to pride month being extended, i will no longer be banging your mother",
    "Meh",
    "well it was a quite dry op but it was ok",
    "Shouldn't have been UN. Needed people to behave and stop whining. Also Admins/Zeus' need to be professional.",
    "The op had a good idea to it. Just felt that the zeus/zeus's didn't take it very seriously.",
    "I liked the checkpoint thing and them local militia coming but the graphics mod from the milsim op would be cool",
  ]},
  { name:"Jawbreaker (Burnt Cigar Ch1)", creator:"SirDanger", year:"21", month:"August", rating:7.50, responses:8, feedback:[
    "A lot of tk'ing and some minor hiccups but all good",
    "HE shotgun go boom",
    "No arty but very cool op went really nice for a night op",
    "Seemed a bit short, had issues with medical and whatnot, combat was limited for 1-1, but when there was action it was alright.",
    "All good, ACE was Gey tho",
    "good",
    "Very good, organized, effective OP. Amazing stealth gameplay and coordinated take downs. Only problem was the OP being too short and medical not working.",
    "Less noise in radio/better coordination, medical working would be good, more enemies",
  ]},
  { name:"Burnt Cigar Part 2", creator:"SirDanger", year:"21", month:"September", rating:8.73, responses:11, feedback:[
    "Cock, balls, a splash of cum perhaps",
    "Was Fun, except for Blue Fuck",
    "Decent op. Some confusion at points. Loved infiltrating the port and trying to talk Spanish.",
    "i liked flying the MH-60 african american hawk",
    "locations did not flow well, otherwise good",
    "needs more explosions",
    "Really good op, good complex objectives with a good overall segway between ops.",
    "Very good operation. John Smith much love america.",
    "Absolutely brilliant, loved the effects, the voice acting, the teamwork and all the explosions and all the cheese.",
  ]},
  { name:"Howling Blizzard", creator:"SirDanger", year:"21", month:"September", rating:7.58, responses:12, feedback:[
    "radio issues",
    "It was very good except for CAS. CAS in this was Horrible",
    "Op was good idea everything was fine but fuck the helicopters",
    "Was alright. Quite a few issues throughout, bit too many enemies perhaps for amount of troops we had at stages.",
    "Good operation, definitely in the top 10 I have done in my 1 year of Arma. For feedback definitely get radios down.",
    "who doesnt love playing peekaboo with ZSU's",
    "liked the squad splits and multi-objective nature of op, friendly fire bad, more enemies would be good",
    "this op was amazing, air to air, very good idea loved it",
    "The BTR's were scary, especially when you have cardiovascular disease so my legs weren't working.",
    "Loved the op only issue was it felt a bit long",
  ]},
  { name:"Vigilant Fury", creator:"SirDanger", year:"21", month:"October", rating:8.00, responses:5, feedback:[
    "Good op :)",
    "good ish op wish their was some air to air but other than that it was good",
    "it was ok died alot but eh it was ok.",
    "Pretty good OP. Think the Zeusing could've been better as AI seemed to spawn in front of players sometimes. Briefings need to be better.",
    "liked the end bit with all the enemies, my ammo provider had his ammo yoinked from him somehow",
  ]},
  { name:"Vigilant Fury 2", creator:"SirDanger", year:"21", month:"November", rating:7.50, responses:4, feedback:[
    "I was Fun",
    "Fuck its good",
    "Needed more depth. Felt very, go here shoot things and leave",
    "I had mod errors at the beginning which effected my general knowledge of what was going on",
  ]},
  { name:"Vigilant Fury 3", creator:"SirDanger", year:"21", month:"November", rating:8.33, responses:3, feedback:[
    "Liked the Op, My team tried to save me",
    "a bit unorganised, also more kills would be nice",
    "More AH1Z's",
  ]},
  { name:"Vigilant Fury 4 (Finale)", creator:"SirDanger", year:"21", month:"November", rating:5.60, responses:5, feedback:[
    "enemy vehicles were fun to destroy, getting shot at by friendly helis was interesting, enemy numbers were good, good overall op",
    "This didn't feel planned or polished at all in my honest opinion, the Zeusing could use some major work.",
    "Kind of meh for a final op. Lacked direction and immersion.",
    "I joined after an extended LOA, I followed leaders and I shot cunts, good shit",
  ]},
  { name:"Valkyrie", creator:"SirDanger", year:"21", month:"December", rating:7.33, responses:3, feedback:[
    "Amazing, Had a Lot of fun.",
    "Stronk NPC's but nice flow",
    "Initial town some of the AI were absolute units just flicking like bots. Long helicopter ride to second objective lacked music. Overall pretty good op.",
  ]},
  { name:"Neptune", creator:"SirDanger", year:"21", month:"January", rating:4.80, responses:5, feedback:[
    "to dark at the start couldnt see shit",
    "WHAT THE FUCK WAS GOING ON THERE WERE NO OBJECTIVES WE DIDNT EVEN GET A BREIF AND NO ONE WAS TALKING OVER THE RADIO",
    "bruh momento",
    "Holy motherfucking shit, apaches, high vis, mg3's, grenade launchers, allahu akbar, pretty epic",
    "the start spawning was wack like the constant spawning under the ship was real bad man. But when it started rolling it became more enjoyable.",
  ]},
];
